/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.14.4.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

export class ProviderClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : <any>window;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    get(pageNumber: number | undefined, pageSize: number | undefined): Promise<PagedResponseOfHealthcareProviderDtoOf> {
        let url_ = this.baseUrl + "/Provider?";
        if (pageNumber === null)
            throw new Error("The parameter 'pageNumber' cannot be null.");
        else if (pageNumber !== undefined)
            url_ += "PageNumber=" + encodeURIComponent("" + pageNumber) + "&";
        if (pageSize === null)
            throw new Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "PageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGet(_response);
        });
    }

    protected processGet(response: Response): Promise<PagedResponseOfHealthcareProviderDtoOf> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = PagedResponseOfHealthcareProviderDtoOf.fromJS(resultData200);
            return result200;
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PagedResponseOfHealthcareProviderDtoOf>(<any>null);
    }
}

export class PagedResponseOfHealthcareProviderDtoOf implements IPagedResponseOfHealthcareProviderDtoOf {
    pageNumber?: number;
    pageSize?: number;
    totalPages?: number;
    totalRecords?: number;
    data?: HealthcareProviderDto[];

    constructor(data?: IPagedResponseOfHealthcareProviderDtoOf) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.pageNumber = _data["pageNumber"];
            this.pageSize = _data["pageSize"];
            this.totalPages = _data["totalPages"];
            this.totalRecords = _data["totalRecords"];
            if (Array.isArray(_data["data"])) {
                this.data = [] as any;
                for (let item of _data["data"])
                    this.data!.push(HealthcareProviderDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): PagedResponseOfHealthcareProviderDtoOf {
        data = typeof data === 'object' ? data : {};
        let result = new PagedResponseOfHealthcareProviderDtoOf();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["pageNumber"] = this.pageNumber;
        data["pageSize"] = this.pageSize;
        data["totalPages"] = this.totalPages;
        data["totalRecords"] = this.totalRecords;
        if (Array.isArray(this.data)) {
            data["data"] = [];
            for (let item of this.data)
                data["data"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IPagedResponseOfHealthcareProviderDtoOf {
    pageNumber?: number;
    pageSize?: number;
    totalPages?: number;
    totalRecords?: number;
    data?: HealthcareProviderDto[];
}

export class HealthcareProviderDto implements IHealthcareProviderDto {
    id?: string;
    orderReports?: OrderReportDto[];
    capacityReports?: CapacityReportDto[];
    stockBalanceReports?: StockBalanceReportDto[];
    receiptReports?: ReceiptReportDto[];

    constructor(data?: IHealthcareProviderDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            if (Array.isArray(_data["orderReports"])) {
                this.orderReports = [] as any;
                for (let item of _data["orderReports"])
                    this.orderReports!.push(OrderReportDto.fromJS(item));
            }
            if (Array.isArray(_data["capacityReports"])) {
                this.capacityReports = [] as any;
                for (let item of _data["capacityReports"])
                    this.capacityReports!.push(CapacityReportDto.fromJS(item));
            }
            if (Array.isArray(_data["stockBalanceReports"])) {
                this.stockBalanceReports = [] as any;
                for (let item of _data["stockBalanceReports"])
                    this.stockBalanceReports!.push(StockBalanceReportDto.fromJS(item));
            }
            if (Array.isArray(_data["receiptReports"])) {
                this.receiptReports = [] as any;
                for (let item of _data["receiptReports"])
                    this.receiptReports!.push(ReceiptReportDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): HealthcareProviderDto {
        data = typeof data === 'object' ? data : {};
        let result = new HealthcareProviderDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        if (Array.isArray(this.orderReports)) {
            data["orderReports"] = [];
            for (let item of this.orderReports)
                data["orderReports"].push(item.toJSON());
        }
        if (Array.isArray(this.capacityReports)) {
            data["capacityReports"] = [];
            for (let item of this.capacityReports)
                data["capacityReports"].push(item.toJSON());
        }
        if (Array.isArray(this.stockBalanceReports)) {
            data["stockBalanceReports"] = [];
            for (let item of this.stockBalanceReports)
                data["stockBalanceReports"].push(item.toJSON());
        }
        if (Array.isArray(this.receiptReports)) {
            data["receiptReports"] = [];
            for (let item of this.receiptReports)
                data["receiptReports"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IHealthcareProviderDto {
    id?: string;
    orderReports?: OrderReportDto[];
    capacityReports?: CapacityReportDto[];
    stockBalanceReports?: StockBalanceReportDto[];
    receiptReports?: ReceiptReportDto[];
}

export class OrderReportDto implements IOrderReportDto {
    id?: string;
    orderDate?: Date | undefined;
    requestedDeliveryDate?: Date | undefined;
    quantity?: number;
    glnReceiver?: string;

    constructor(data?: IOrderReportDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.orderDate = _data["orderDate"] ? new Date(_data["orderDate"].toString()) : <any>undefined;
            this.requestedDeliveryDate = _data["requestedDeliveryDate"] ? new Date(_data["requestedDeliveryDate"].toString()) : <any>undefined;
            this.quantity = _data["quantity"];
            this.glnReceiver = _data["glnReceiver"];
        }
    }

    static fromJS(data: any): OrderReportDto {
        data = typeof data === 'object' ? data : {};
        let result = new OrderReportDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["orderDate"] = this.orderDate ? this.orderDate.toISOString() : <any>undefined;
        data["requestedDeliveryDate"] = this.requestedDeliveryDate ? this.requestedDeliveryDate.toISOString() : <any>undefined;
        data["quantity"] = this.quantity;
        data["glnReceiver"] = this.glnReceiver;
        return data; 
    }
}

export interface IOrderReportDto {
    id?: string;
    orderDate?: Date | undefined;
    requestedDeliveryDate?: Date | undefined;
    quantity?: number;
    glnReceiver?: string;
}

export class CapacityReportDto implements ICapacityReportDto {
    id?: string;
    date?: Date;
    numberOfVials?: number;
    supplierId?: string;

    constructor(data?: ICapacityReportDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            this.numberOfVials = _data["numberOfVials"];
            this.supplierId = _data["supplierId"];
        }
    }

    static fromJS(data: any): CapacityReportDto {
        data = typeof data === 'object' ? data : {};
        let result = new CapacityReportDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["date"] = this.date ? this.date.toISOString() : <any>undefined;
        data["numberOfVials"] = this.numberOfVials;
        data["supplierId"] = this.supplierId;
        return data; 
    }
}

export interface ICapacityReportDto {
    id?: string;
    date?: Date;
    numberOfVials?: number;
    supplierId?: string;
}

export class StockBalanceReportDto implements IStockBalanceReportDto {
    id?: string;
    date?: Date;
    supplierId?: string;
    numberOfVials?: number;
    numberOfDosages?: number;

    constructor(data?: IStockBalanceReportDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
            this.supplierId = _data["supplierId"];
            this.numberOfVials = _data["numberOfVials"];
            this.numberOfDosages = _data["numberOfDosages"];
        }
    }

    static fromJS(data: any): StockBalanceReportDto {
        data = typeof data === 'object' ? data : {};
        let result = new StockBalanceReportDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["date"] = this.date ? this.date.toISOString() : <any>undefined;
        data["supplierId"] = this.supplierId;
        data["numberOfVials"] = this.numberOfVials;
        data["numberOfDosages"] = this.numberOfDosages;
        return data; 
    }
}

export interface IStockBalanceReportDto {
    id?: string;
    date?: Date;
    supplierId?: string;
    numberOfVials?: number;
    numberOfDosages?: number;
}

export class ReceiptReportDto implements IReceiptReportDto {
    id?: string;
    deliveryDate?: Date | undefined;
    expectedDeliveryDate?: Date;
    numberOfVials?: number;
    glnReceiver?: string;
    supplierId?: string;

    constructor(data?: IReceiptReportDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.deliveryDate = _data["deliveryDate"] ? new Date(_data["deliveryDate"].toString()) : <any>undefined;
            this.expectedDeliveryDate = _data["expectedDeliveryDate"] ? new Date(_data["expectedDeliveryDate"].toString()) : <any>undefined;
            this.numberOfVials = _data["numberOfVials"];
            this.glnReceiver = _data["glnReceiver"];
            this.supplierId = _data["supplierId"];
        }
    }

    static fromJS(data: any): ReceiptReportDto {
        data = typeof data === 'object' ? data : {};
        let result = new ReceiptReportDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["deliveryDate"] = this.deliveryDate ? this.deliveryDate.toISOString() : <any>undefined;
        data["expectedDeliveryDate"] = this.expectedDeliveryDate ? this.expectedDeliveryDate.toISOString() : <any>undefined;
        data["numberOfVials"] = this.numberOfVials;
        data["glnReceiver"] = this.glnReceiver;
        data["supplierId"] = this.supplierId;
        return data; 
    }
}

export interface IReceiptReportDto {
    id?: string;
    deliveryDate?: Date | undefined;
    expectedDeliveryDate?: Date;
    numberOfVials?: number;
    glnReceiver?: string;
    supplierId?: string;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data; 
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}